### ISSUE TITLE
Необычное значение ключа --daemon

### ISSUE THREAD

**Issue by ehlyzov** [akil-io/dpe#1]
Повсеместно такой ключ означает запуск процесса в режиме демона, т.е. ([в фоновом режиме](https://ru.wikipedia.org/wiki/%D0%94%D0%B5%D0%BC%D0%BE%D0%BD_%28%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B0%29)) у нас же ровно наоборот – ключ используется для запуска сервиса DPE на переднем плане. Мне это сразу сломало мозг, ставлю на то, что многим другим тоже сломает. 

Предлагаю заменить ключ на `--no-daemon`, как в **pm2**.

**Comment by FenixDeveloper** [comment]
Вообще это внутренний ключ который используется при запуске процесса той или иной оберткой (нашей или pm2). Рабочий запуск предполагается как dpe service start, возможно сюда добавлю ключ --no-daemon чтобы вывести на передний план. Так нормально?

**Comment by ehlyzov** [comment]
Да, давай так. Могу подсобить. Открою новый тикет.
