### ISSUE TITLE
dpe service reset работает не так как ожидается

### ISSUE THREAD

**Issue by ehlyzov** [akil-io/dpe#2]
Ожидается, что команда сбросит текущую конфигурацию на настройки по-умолчанию. Вместо этого она делает то, что, вероятно, должна делать `dpe service purge` да и то не факт, можно руками стереть `~/.dpe`. В общем, целесообразность команды ставится под сомнение, предлагаю её устранить.

**Comment by FenixDeveloper** [comment]
Согласен, неудачное название. Но предлагаю заменить на clear - идея в очистке системы от рабочей директории и прочих файлов dpe если они раскиданы вдруг (можно в конфигах поменять).

**Comment by ehlyzov** [comment]
Изменено в 5658ea32
