### ISSUE TITLE
Путь к конфигу при командах управления сервисом.

### ISSUE THREAD

**Issue by ehlyzov** [akil-io/dpe#3]
Было бы здорово, если при для команд

```
dpe service configure
dpe service start
dpe service stop
dpe service status
```

можно было указывать путь к текущей конфигурации (по-умолчанию `~/.dpe`). Это бы позволило в спокойном режиме запускать несколько dpe-сервисов в рамках одного сервера.

**Comment by FenixDeveloper** [comment]
Ок, добавлю в ближайших патчах.

**Comment by FenixDeveloper** [comment]
В большинстве функций с параметров -с, но в dpe app add с ключом -k
