### ISSUE TITLE
DPE не всегда осуществляет проверку на наличие ядра

### ISSUE THREAD

**Issue by ehlyzov** [akil-io/dpe#4]
При запуске с ключом `--daemon` проверка не производится и сервис спокойно стартует. Его функциональность при этом не нарушена. Насколько необходимо условие запуска как минимум с одним ядром?

**Comment by FenixDeveloper** [comment]
Требование устранено, в дальнейшем возвращать не будем, просто единственной доступной функций после пустого запуска будет выбор ядра.
