### ISSUE TITLE
Документация: ядра, модули и приложения.

### ISSUE THREAD

**Issue by ehlyzov** [akil-io/dpe#6]
Сейчас мое понимание заключается в том, что DPE работает с комонентами. Компонент определяется JSON-файлом (обычно называется dpe.json) в котором перечисляются nodejs-модули для подключения. Компоненты могут иметь разный уровень доступа: core, module, app. 

core – запуск компонента на уровне ядра
module – запуск компонента на уровне модуля
app – запуск компонента в песочнице

В текущей версии есть какие-либо различия между этими уровнями? Чем конкретно сейчас отличается запуск в нормальном режиме от режима ядра? Почему есть требование, чтобы при запуске сервиса был хотя бы один компонент, запускающийся в режиме ядра? Есть ли семантическая разница между понятиями ядра и компонента, запускающегося на уровне ядра?

**Comment by FenixDeveloper** [comment]
Уточнение - dpe.json на данный момент описывает модули (и ядра что тоже самое по факту), синтаксис описания компонент будет изменен к версии 1.5

На данный момент ядро встроено в систему жестко, связано с проблемой загрузки цикличных зависимостей в новом менеджере пакетов, планируется устранить к 1.5 вместе с изменением синтаксиса описания компонент. По этой причине требование запуска хотя бы с одним компонентом устранено. Разница между функциями сейчас только в том что ядро нельзя выгружать и переопределять, также оно не экспортируется по сети.

Сейчас загружаются модули и ядра, которые могут включать в себя только наборы функций. Приложения на данный момент отсутствуют, в проработке в одном пакете с перечисленным выше.

Ядро имеет следующее отличие - оно определяется только при старте системы, нельзя выгружать или заменять его функции (но можно вешать хук).

Приложения отличается от модулей и ядра тем что может содержать шаблоны процессов, сигналов, ссылки на модули и ядра и отдельные компоненты.
